/*
 * This file is part of javaducks, licensed under the MIT License.
 *
 * Copyright (c) 2023-2024 Seiama
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.seiama.javaducks.injection;

import java.nio.file.Path;
import org.springframework.stereotype.Component;

@Component
public class DuckInjection implements Injection {
  @Override
  public boolean canInject(final Path file) {
    return file.toString().endsWith(".html");
  }

  @Override
  public String inject(final String line, final Path file, final String project, final String version) {
    if (line.contains("<!-- Generated by")) {
      return """
        <!--          ,~~.                _                      _            _              -->
        <!--         (  6 )-_,           (_) __ ___   ____ _  __| |_   _  ___| | _____       -->
        <!--    (\\___ )=='-'             | |/ _` \\ \\ / / _` |/ _` | | | |/ __| |/ / __|      -->
        <!--     \\ .   ) )               | | (_| |\\ V / (_| | (_| | |_| | (__|   <\\__ \\      -->
        <!--      \\ `-' /               _/ |\\__,_| \\_/ \\__,_|\\__,_|\\__,_|\\___|_|\\_\\___/      -->
        <!--   ~'`~'`~'`~'`~           |__/                                                  -->
        %s
        """.formatted(line);
    }
    return line;
  }
}
